<?php
// =============================================
// Pixel & GTM Tracking Settings
// =============================================
require_once __DIR__ . '/../includes/admin-layout.php';

if (adminRole() !== 'admin') {
    echo "<script>alert('আপনার এই পেজে প্রবেশের অনুমতি নেই'); window.location='/admin/dashboard.php';</script>";
    exit;
}

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $keys = [
        'pixel_enabled' => isset($_POST['pixel_enabled']) ? '1' : '0',
        'gtm_enabled' => isset($_POST['gtm_enabled']) ? '1' : '0',
        'server_tracking_enabled' => isset($_POST['server_tracking_enabled']) ? '1' : '0',
        'meta_pixel_id' => trim($_POST['meta_pixel_id']),
        'gtm_container_id' => trim($_POST['gtm_container_id']),
        'server_side_token' => trim($_POST['server_side_token']),
        'server_side_url' => trim($_POST['server_side_url']),
    ];
    
    foreach ($keys as $key => $val) {
        updateSetting($key, $val);
    }
    
    echo "<script>alert('ট্র্যাকিং সেটিংস আপডেট হয়েছে!'); window.location='/admin/tracking-settings.php';</script>";
    exit;
}

$s = getAllSettings();
?>

<div class="admin-card-head" style="padding:0 0 20px 0; border:none; background:transparent">
    <div>
        <h1 class="admin-page-title">ট্র্যাকিং ও মার্কেটিং সেটিংস</h1>
        <p class="admin-page-subtitle">Meta Pixel, Google Tag Manager এবং CAPI কনফিগার করুন।</p>
    </div>
</div>

<form method="POST">
    <div class="form-grid form-grid-2" style="align-items:start">
        
        <!-- Client Side -->
        <div>
            <!-- Meta Pixel -->
            <div class="admin-form-card mb-4">
                <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:20px">
                    <h3 class="admin-form-title" style="margin:0;color:#1877f2"><i class="fab fa-facebook"></i> Meta Pixel</h3>
                    <label class="toggle">
                        <input type="checkbox" name="pixel_enabled" <?= ($s['pixel_enabled'] ?? '0') === '1' ? 'checked' : '' ?>>
                        <span class="toggle-slider"></span>
                    </label>
                </div>
                
                <div class="form-group mb-4">
                    <label class="form-label">Pixel ID</label>
                    <input type="text" name="meta_pixel_id" id="metaPixelId" class="form-control" value="<?= htmlspecialchars($s['meta_pixel_id'] ?? '') ?>" placeholder="e.g. 123456789012345">
                    <div class="form-hint">এটি সেট করলে ওয়েবসাইটে স্বয়ংক্রিয়ভাবে Base Code এবং PageView ইভেন্ট ফায়ার হবে।</div>
                </div>

                <div class="code-preview" id="pixelCodePreview">
                    <!-- Preview generated by JS -->
                </div>
            </div>

            <!-- GTM -->
            <div class="admin-form-card">
                <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:20px">
                    <h3 class="admin-form-title" style="margin:0;color:#fbbc04"><i class="fab fa-google"></i> Google Tag Manager</h3>
                    <label class="toggle">
                        <input type="checkbox" name="gtm_enabled" <?= ($s['gtm_enabled'] ?? '0') === '1' ? 'checked' : '' ?>>
                        <span class="toggle-slider"></span>
                    </label>
                </div>
                
                <div class="form-group mb-4">
                    <label class="form-label">Container ID (GTM-XXXXXX)</label>
                    <input type="text" name="gtm_container_id" id="gtmContainerId" class="form-control" value="<?= htmlspecialchars($s['gtm_container_id'] ?? '') ?>" placeholder="e.g. GTM-WXYZ123">
                    <div class="form-hint">আমাদের সিস্টেমে ডেটালেয়ার (dataLayer) অ্যাড করা আছে। GTM এর মাধ্যমে আপনি Google Analytics (GA4) সেটআপ করতে পারবেন।</div>
                </div>

                <div class="code-preview" id="gtmCodePreview">
                    <!-- Preview generated by JS -->
                </div>
            </div>
        </div>

        <!-- Server Side (CAPI) -->
        <div class="admin-form-card">
            <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:20px;padding-bottom:16px;border-bottom:1px solid var(--border)">
                <h3 class="admin-form-title" style="margin:0"><i class="fa fa-server"></i> Server-Side Tracking (CAPI)</h3>
                <label class="toggle">
                    <input type="checkbox" name="server_tracking_enabled" <?= ($s['server_tracking_enabled'] ?? '0') === '1' ? 'checked' : '' ?>>
                    <span class="toggle-slider"></span>
                </label>
            </div>
            
            <p style="font-size:0.875rem;color:var(--text3);margin-bottom:20px;line-height:1.6">
                iOS 14 আপডেট এবং অ্যাড ব্লকারের কারণে অনেক ব্রাউজার ক্লায়েন্ট-সাইড পিক্সেল ব্লক করে দেয়। 
                কনভার্সন ট্র্যাকিং নিখুঁত করতে (বিশেষ করে Purchase Event) সার্ভার-সাইড ট্র্যাকিং খুবই জরুরি।
            </p>

            <div class="form-group mb-4">
                <label class="form-label">Access Token (CAPI Token)</label>
                <textarea name="server_side_token" class="form-control" rows="4" placeholder="EAAB..."><?= htmlspecialchars($s['server_side_token'] ?? '') ?></textarea>
                <div class="form-hint">Meta Events Manager থেকে Generate Access Token করে এখানে পেস্ট করুন।</div>
            </div>

            <div class="form-group mb-4">
                <label class="form-label">Custom Server URL (Optional)</label>
                <input type="url" name="server_side_url" class="form-control" value="<?= htmlspecialchars($s['server_side_url'] ?? '') ?>" placeholder="https://st.yourdomain.com/events">
                <div class="form-hint">যদি আপনি Stape.io বা নিজস্ব GTM Server Container ব্যবহার করেন, তবে সেই URL দিন। ফাঁকা রাখলে ডিফল্ট Facebook Graph API ব্যবহার হবে।</div>
            </div>

            <div class="alert-info" style="background:rgba(59,130,246,0.1);color:#60a5fa;padding:12px;border-radius:var(--radius-sm);font-size:0.85rem">
                <i class="fa fa-info-circle"></i> <strong>কিভাবে কাজ করে:</strong><br>
                যখন কোনো গ্রাহক অর্ডার প্লেস করে, তখন আমাদের সার্ভার থেকে সরাসরি ফেসবুকের সার্ভারে (অথবা আপনার Custom Server-এ) Purchase ডেটা পাঠানো হয়। 
                এতে কোনো ডেটা মিস হওয়ার সম্ভাবনা থাকে না।
            </div>
        </div>

    </div>

    <div style="position:sticky;bottom:20px;background:var(--card);padding:20px;border-radius:var(--radius);border:1px solid var(--border);margin-top:20px;box-shadow:var(--shadow-lg);display:flex;justify-content:flex-end">
        <button type="submit" class="btn-admin btn-admin-primary btn-lg"><i class="fa fa-save"></i> ট্র্যাকিং সেটিং সেভ করুন</button>
    </div>
</form>

<script>
if (window.innerWidth <= 1024) document.getElementById('adminMenuBtn').style.display = 'flex';
setTimeout(() => updateTrackingPreview(), 100);
</script>

            </div><!-- .admin-content -->
        </main>
    </div><!-- .admin-wrapper -->
    <script src="/assets/js/admin.js"></script>
</body>
</html>
